// React/src/App.js
import React, { useCallback, useState, useMemo, useRef } from 'react';
    
import 'devextreme/dist/css/dx.light.css';
import './App.css';

import DataGrid, { Column, Editing, Button, Toolbar } from 'devextreme-react/data-grid';
import Popup, { ToolbarItem } from 'devextreme-react/popup';
import Form, { Item, GroupItem, Label } from 'devextreme-react/form';
import validationEngine from 'devextreme/ui/validation_engine';
import AddRowButton from 'devextreme-react/button';
import LabelTemplate from './LabelTemplate.js';
import LabelNotesTemplate from './LabelNotesTemplate.js';
import 'devextreme-react/text-area';

import ArrayStore from 'devextreme/data/array_store';

import { employees } from './data.js';

import { 
    validationRules, 
    positionEditorOptions, 
    notesEditorOptions, 
    phoneEditorOptions 
} from './ValidationRulesAndEditorOptions.js';

const employeeStore = new ArrayStore({
    data: employees,
    key: "ID",
});

const validationGroupName = "gridForm";
const App = () => {
    const gridRef = useRef(null);
    const [{isNewRecord, formData, visible}, setPopupState] = useState({});

    const showPopup = useCallback((isNewRecord, formData) => { 
        setPopupState({isNewRecord, formData, visible: true});
    }, []);

    const hidePopup = useCallback(() => { 
        setPopupState({visible: false});
    }, []);

    const confirmChanges = useCallback(() => { 
        const result = validationEngine.validateGroup(validationGroupName);
     
        if (result.isValid) {

            if (isNewRecord)
                employeeStore.insert(formData); 
            else 
                employeeStore.update(formData["ID"], formData);

            gridRef.current.instance.refresh(true);
            hidePopup();
        }
    }, [isNewRecord, formData, hidePopup]);

    const confirmBtnOptions = useMemo(() => {
        return { 
            text: "Confirm", 
            type: "success",
            onClick: confirmChanges 
        }
    }, [confirmChanges]);
    
    const cancelBtnOptions = useMemo(() => { 
        return { 
            text: "Cancel", 
            onClick: hidePopup
        }
    }, [hidePopup]);

    const editRow = useCallback((e) => { 
        showPopup(false, e.row.data);
    }, [showPopup]);

    const addRow = useCallback(() => { 
        showPopup(true, {});
    }, [showPopup]);

    return (
        <React.Fragment>
            <DataGrid
                dataSource={{store: employeeStore}}
                ref={gridRef}
                showBorders={true}
                repaintChangesOnly={true}
            >
                <Editing 
                    allowUpdating={true}
                    allowAdding={true}
                    allowDeleting={true}
                    useIcons={true}
                    mode="popup" 
                />
                <Column dataField="FirstName" dataType="string" />
                <Column dataField="LastName" dataType="string" />
                <Column dataField="BirthDate" dataType="date" />
                <Column dataField="Position" width={170} dataType="string" />
                <Column dataField="HireDate" dataType="date" />
                <Column dataField="Address" dataType="string" />
                <Column type="buttons">
                    <Button name="edit" onClick={editRow} />
                    <Button name="delete" />
                </Column>
                <Toolbar>
                    <Item location="after">
                        <AddRowButton
                            icon="plus"
                            onClick={addRow} />
                    </Item>
                </Toolbar>
            </DataGrid>
            { visible ? (
                <Popup 
                    title={isNewRecord ? "Add" : "Edit"}
                    hideOnOutsideClick={true}
                    visible={true}
                    height={"auto"}
                    onHiding={hidePopup}
                >
                    <ToolbarItem 
                        widget="dxButton"
                        location="after"
                        toolbar="bottom"
                        options={confirmBtnOptions} 
                    />
                    <ToolbarItem 
                        widget="dxButton"
                        location="after"
                        toolbar="bottom"
                        options={cancelBtnOptions} 
                    />
                    
                    <Form 
                        validationGroup={validationGroupName}
                        formData={formData} 
                    >
                        <GroupItem colCount={2} >
                            <Item dataField="FirstName" validationRules={validationRules.firstName} >
                                <Label render={LabelTemplate("user")} />
                            </Item>
                            <Item dataField="Position" editorType="dxSelectBox" editorOptions={positionEditorOptions} >
                                <Label render={LabelTemplate("info")} />
                            </Item>
                            <Item dataField="LastName" validationRules={validationRules.lastName} >
                                <Label render={LabelTemplate("user")} />
                            </Item>
                            <Item dataField="Address">
                                <Label render={LabelTemplate("home")} />
                            </Item>
                            <Item dataField="BirthDate" editorType="dxDateBox" validationRules={validationRules.birthDate} >
                                <Label render={LabelTemplate("event")} />
                            </Item>
                            <Item dataField="HireDate" editorType="dxDateBox" >
                                <Label render={LabelTemplate("event")} />
                            </Item>
                            <Item dataField="Notes" colSpan={2} editorType="dxTextArea" editorOptions={notesEditorOptions}>
                                <Label render={LabelNotesTemplate} />
                            </Item>
                            <Item dataField="Phone" editorOptions={phoneEditorOptions} validationRules={validationRules.phone}>
                                <Label render={LabelTemplate("tel")} />
                            </Item>
                            <Item dataField="Email" validationRules={validationRules.email}>
                                <Label render={LabelTemplate("email")} />
                            </Item>
                        </GroupItem>
                    </Form>
                </Popup>
            ) : null }
            
        </React.Fragment>
    );
}

export default App;

// Angular/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { DxDataGridComponent } from 'devextreme-angular';

import validationEngine from 'devextreme/ui/validation_engine';

import ArrayStore from 'devextreme/data/array_store';
import { Employee, Service } from './app.service';

type PositionEditorOptions = {
    items: string[], 
    searchEnabled: boolean
}

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css'],
    providers: [Employee, Service]
})

export class AppComponent {
    @ViewChild("grid", {static: false}) grid: DxDataGridComponent;

    employees: Employee[];
    employeeStore: ArrayStore;

    formData: Employee[];
    isNewRecord = true;
    visible = false;

    positionEditorOptions: PositionEditorOptions;
    notesEditorOptions = { height: 90, maxLength: 200 };
    phoneEditorOptions = { 
        mask: "+1 (X00) 000-0000", 
        maskRules: { X: /[02-9]/ },
        maskInvalidMessage: "The phone must have a correct USA phone format", 
    };

    labelTemplates = [
        { name: "name", icon: "dx-icon-user" },
        { name: "position", icon: "dx-icon-info" },
        { name: "date", icon: "dx-icon-event" },
        { name: "address", icon: "dx-icon-home" },
        { name: "phone", icon: "dx-icon-tel" },
        { name: "email", icon: "dx-icon-email" },
    ];

    get validationGroupName() { 
        return "gridForm"; 
    }

    showPopup = (isNewRecord, formData) => {
        this.formData = formData;
        this.isNewRecord = isNewRecord;
        this.visible = true;
    };

    hidePopup = () => { 
        this.visible = false;
    };

    confirmChanges = () => {
        const result = validationEngine.validateGroup(this.validationGroupName);
     
        if (!result.isValid)
            return;

        if (this.isNewRecord)
            this.employeeStore.insert(this.formData); 
        else 
            this.employeeStore.update(this.formData["ID"], this.formData);

        this.grid.instance.refresh(true);
        this.hidePopup();
    };

    addRow = () => {
        this.showPopup(true, {});
    };

    editRow = (e) => {
        this.showPopup(false, {...e.row.data});
    };

    constructor(service: Service) {
        this.employees = service.getEmployees();

        this.employeeStore = new ArrayStore({
            data: this.employees,
            key: "ID",
        });  

        this.positionEditorOptions = { items: service.getPositions(), searchEnabled: true };
    }
}
<dx-data-grid 
    #grid
    [dataSource]="{ store: this.employeeStore }"
    [showBorders]="true"
    [repaintChangesOnly]="true"
>
    <dxo-editing
        [allowUpdating]="true"
        [allowAdding]="true"
        [allowDeleting]="true"
        [useIcons]="true"
        mode="popup"
    > </dxo-editing>
    <dxi-column dataField="FirstName" dataType="string"></dxi-column>
    <dxi-column dataField="LastName" dataType="string"></dxi-column>
    <dxi-column dataField="BirthDate" dataType="date"></dxi-column>
    <dxi-column dataField="Position" dataType="string"></dxi-column>
    <dxi-column dataField="HireDate" dataType="date"></dxi-column>
    <dxi-column dataField="Address" dataType="string"></dxi-column>
    <dxi-column type="buttons">
        <dxi-button name="edit" [onClick]="editRow"></dxi-button>
        <dxi-button name="delete"></dxi-button>
    </dxi-column>
    <dxo-toolbar>
        <dxi-item location="after">
            <div *dxTemplate>
                <dx-button icon="plus" (onClick)="addRow()"></dx-button>
            </div>
        </dxi-item>
    </dxo-toolbar>
</dx-data-grid>

<dx-popup 
    *ngIf="visible"
    [title]="isNewRecord ? 'Add' : 'Edit'"
    [hideOnOutsideClick]="true"
    height="auto"
    [visible]="true"
    onHiding="hidePopup"
>
    <dxi-toolbar-item 
        widget="dxButton"
        location="after"
        toolbar="bottom"
        [options]="{ 
            text: 'Confirm', 
            type: 'success',
            onClick: confirmChanges 
        }"
    > </dxi-toolbar-item>
    <dxi-toolbar-item 
        widget="dxButton"
        location="after"
        toolbar="bottom"
        [options]="{ 
            text: 'Cancel',
            onClick: hidePopup 
        }"
    > </dxi-toolbar-item>
            
    <div *dxTemplate="let data of 'content'">
        <dx-form
            [validationGroup]="validationGroupName"
            [formData]="formData"
        >
            <dxi-item itemType="group" [colCount]="2" >
                <dxi-item dataField="FirstName" >
                    <dxi-validation-rule
                        type="required"
                        message="First Name is required."
                    ></dxi-validation-rule>
                    <dxo-label template="name"></dxo-label>
                </dxi-item>
                <dxi-item
                    dataField="Position"
                    editorType="dxSelectBox"
                    [editorOptions]="positionEditorOptions"
                >
                    <dxo-label template="position"></dxo-label>
                </dxi-item>
                <dxi-item dataField="LastName" >
                    <dxi-validation-rule
                        type="required"
                        message="Last Name is required."
                    ></dxi-validation-rule>
                    <dxo-label template="name"></dxo-label>
                </dxi-item>
                <dxi-item dataField="Address">
                    <dxo-label template="address"></dxo-label>
                </dxi-item>
                <dxi-item
                    dataField="BirthDate"
                    editorType="dxDateBox"
                >
                    <dxi-validation-rule
                        type="required"
                        message="Birth Date is required."
                        invalidDateMessage="The date must have the following format: mm/dd/yyyy" 
                    ></dxi-validation-rule>
                    <dxo-label template="date"></dxo-label>
                </dxi-item>
                <dxi-item
                    dataField="HireDate"
                    editorType="dxDateBox"
                >
                    <dxo-label template="date"></dxo-label>
                </dxi-item>
                <dxi-item
                    dataField="Notes"
                    editorType="dxTextArea"
                    [editorOptions]="notesEditorOptions"
                    [colSpan]="2"
                >
                    <dxo-label template="notes"></dxo-label>
                </dxi-item>
                <dxi-item dataField="Phone" [editorOptions]="phoneEditorOptions">
                    <dxi-validation-rule
                        type="required"
                        message="Phone number is required."
                    ></dxi-validation-rule>
                    <dxo-label template="phone"></dxo-label>
                </dxi-item>
                <dxi-item dataField="Email">
                    <dxi-validation-rule
                        type="email"
                        message="Email is incorrect."
                    ></dxi-validation-rule>
                    <dxo-label template="email"></dxo-label>
                </dxi-item>
            </dxi-item>
      
            <ng-container *ngFor="let label of labelTemplates">
                <div *dxTemplate="let data of label.name">
                    <div><i class="dx-icon {{ label.icon }}"></i>{{ data.text }}</div>
                </div>
            </ng-container>
      
            <div *dxTemplate="let data of 'notes'">
                <div id="template-content">
                    <i id="helpedInfo" class="dx-icon dx-icon-info"></i>
                    Additional
                    <br />
                    {{ data.text }}
                </div>
      
                <dx-tooltip
                    target="#helpedInfo"
                    showEvent="mouseenter"
                    hideEvent="mouseleave"
                >
                    <div *dxTemplate="let data = data; of: 'content'">
                        <div id="tooltip-content">
                            This field must not exceed 200 characters
                        </div>
                    </div>
                </dx-tooltip>
            </div>
        </dx-form>
    </div>
</dx-popup>
